BEGIN;

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wechat_open_id varchar(64) NOT NULL,
    nickname varchar(64) NOT NULL DEFAULT '',
    avatar_url text NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uk_app_user_wechat_open_id ON app_user (wechat_open_id);

CREATE TABLE user_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_session_app_user
        FOREIGN KEY (app_user_id) REFERENCES app_user (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX uk_user_session_token_hash ON user_session (token_hash);
CREATE INDEX idx_user_session_app_user_id ON user_session (app_user_id);
CREATE INDEX idx_user_session_expires_at ON user_session (expires_at);

CREATE TABLE match_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_name varchar(80) NOT NULL,
    round_name varchar(40) NOT NULL DEFAULT '',
    home_team varchar(80) NOT NULL,
    away_team varchar(80) NOT NULL,
    venue varchar(120) NOT NULL,
    venue_address varchar(200) NOT NULL DEFAULT '',
    kickoff_at timestamptz NOT NULL,
    admission_at timestamptz,
    booking_start_at timestamptz NOT NULL,
    booking_end_at timestamptz NOT NULL,
    capacity integer NOT NULL,
    reserved_count integer NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    cover_image_url text NOT NULL DEFAULT '',
    notice text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_match_event_capacity CHECK (capacity >= 0),
    CONSTRAINT ck_match_event_reserved_count CHECK (reserved_count >= 0 AND reserved_count <= capacity),
    CONSTRAINT ck_match_event_booking_window CHECK (booking_end_at > booking_start_at),
    CONSTRAINT ck_match_event_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'SOLD_OUT', 'CANCELLED', 'FINISHED'))
);

CREATE INDEX idx_match_event_status_kickoff_at ON match_event (status, kickoff_at);

CREATE TABLE news_article (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(120) NOT NULL,
    summary varchar(300) NOT NULL DEFAULT '',
    cover_image_url text NOT NULL DEFAULT '',
    content text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_news_article_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX idx_news_article_status_published_at ON news_article (status, published_at DESC);

CREATE TABLE ticket_reservation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no varchar(32) NOT NULL,
    match_event_id bigint NOT NULL,
    app_user_id bigint NOT NULL,
    attendee_name varchar(64) NOT NULL,
    attendee_phone varchar(20) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'RESERVED',
    ticket_code varchar(48) NOT NULL,
    reserved_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at timestamptz,
    verified_at timestamptz,
    verified_gate varchar(40) NOT NULL DEFAULT '',
    verified_by varchar(64) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT fk_ticket_reservation_match_event
        FOREIGN KEY (match_event_id) REFERENCES match_event (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ticket_reservation_app_user
        FOREIGN KEY (app_user_id) REFERENCES app_user (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_ticket_reservation_status CHECK (status IN ('RESERVED', 'CANCELLED', 'VERIFIED')),
    CONSTRAINT ck_ticket_reservation_phone CHECK (attendee_phone ~ '^1[3-9][0-9]{9}$')
);

CREATE UNIQUE INDEX uk_ticket_reservation_order_no ON ticket_reservation (order_no);
CREATE UNIQUE INDEX uk_ticket_reservation_ticket_code ON ticket_reservation (ticket_code);
CREATE UNIQUE INDEX uk_ticket_reservation_active_user_match
    ON ticket_reservation (match_event_id, app_user_id)
    WHERE status <> 'CANCELLED';
CREATE INDEX idx_ticket_reservation_match_event_id ON ticket_reservation (match_event_id);
CREATE INDEX idx_ticket_reservation_app_user_id ON ticket_reservation (app_user_id);
CREATE INDEX idx_ticket_reservation_attendee_phone ON ticket_reservation (attendee_phone);

CREATE TABLE staff_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_name varchar(64) NOT NULL,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_staff_session_token_hash ON staff_session (token_hash);
CREATE INDEX idx_staff_session_expires_at ON staff_session (expires_at);

CREATE TABLE ticket_verification_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_reservation_id bigint,
    ticket_code varchar(48) NOT NULL,
    result varchar(24) NOT NULL,
    gate_name varchar(40) NOT NULL DEFAULT '',
    staff_name varchar(64) NOT NULL DEFAULT '',
    detail varchar(300) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_verification_log_ticket_reservation
        FOREIGN KEY (ticket_reservation_id) REFERENCES ticket_reservation (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_ticket_verification_log_result
        CHECK (result IN ('VERIFIED', 'ALREADY_VERIFIED', 'NOT_FOUND', 'CANCELLED', 'INVALID'))
);

CREATE INDEX idx_ticket_verification_log_ticket_reservation_id
    ON ticket_verification_log (ticket_reservation_id);
CREATE INDEX idx_ticket_verification_log_created_at
    ON ticket_verification_log (created_at DESC);

COMMIT;

